language: python

dist: xenial
os: linux

python:
  - "3.7"

install:
  - pip install flake8
  - pip install flake8-docstrings
  - pip install pylint
  - pip install pylint-django
  - pip install pylint-quotes
  - pip install -r requirements.txt
    # - npm install -g stylelint
    # - npm install stylelint-config-standard --save-dev
    # - npm install -g eslint
    # - npm install -g eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node

script:
  - find -name "*.py" -not -path "*/migrations/*" -not -name "apps.py" -not -name "wsgi.py" -not -name "manage.py" -not -name "settings.py" | xargs pylint --load-plugins pylint_django
  - flake8 . --exclude migrations,tests.py,__init__.py,apps.py,manage.py,settings.py --per-file-ignores='philmnight/settings.py:E501'
    # - stylelint **/static/**/*.css
    # - eslint . --ignore-pattern '/staticfiles/*'
