# Generated by Django 3.2 on 2021-10-16 15:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(default=1, null=True, unique=True)),
                ('score', models.DecimalField(decimal_places=1, default=-1, max_digits=3, null=True)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(default='', null=True)),
                ('tagline', models.TextField(default='', null=True)),
                ('watched', models.BooleanField(default=False)),
                ('_genres', models.TextField(default='', null=True)),
                ('poster_path', models.CharField(default='', max_length=100, null=True)),
                ('backdrop_path', models.CharField(default='', max_length=100, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('submitting_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_votes', models.TextField(blank=True, default='')),
                ('last_vote', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Philmnight', max_length=80)),
                ('logo', models.ImageField(default='logo/default.png', upload_to='config/')),
                ('logo_favicon', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('shortlist_length', models.IntegerField(default=8)),
                ('last_shortlist', models.DateTimeField()),
                ('odd_weeks', models.BooleanField(default=False)),
                ('stylesheet', models.FileField(default='config/stylesheet.css', upload_to='config/')),
                ('shortlist', models.ManyToManyField(to='film_management.Film')),
            ],
        ),
    ]
