# Generated by Django 2.2.2 on 2019-11-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_id',
            field=models.CharField(blank=True, max_length=70, unique=True),
        ),
    ]
