# Generated by Django 3.2 on 2021-10-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0002_auto_20211019_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmconfig',
            old_name='voting_period_length',
            new_name='voting_length',
        ),
    ]
