# Generated by Django 2.2.2 on 2019-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0002_film_film_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlist_length', models.IntegerField(default=8)),
            ],
        ),
    ]
