# Generated by Django 2.2.2 on 2019-11-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0003_filmconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
