# Generated by Django 2.2.2 on 2019-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0004_film_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='submitting_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
