# Generated by Django 2.2.2 on 2019-11-25 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0005_film_submitting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='submitting_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
