# Generated by Django 2.2.2 on 2019-11-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0006_auto_20191125_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmconfig',
            name='shortlist',
            field=models.ManyToManyField(to='film_management.Film'),
        ),
    ]
