# Generated by Django 2.2.2 on 2019-11-25 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0007_filmconfig_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmconfig',
            name='last_shortlist',
            field=models.DateTimeField(default=datetime.date(1, 1, 1)),
            preserve_default=False,
        ),
    ]
