# Generated by Django 2.2.2 on 2019-11-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0008_filmconfig_last_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
