# Generated by Django 2.2.2 on 2019-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0009_film_watched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentVotes', models.TextField(blank=True)),
            ],
        ),
    ]
