# Generated by Django 2.2.2 on 2019-11-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0011_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='currentVotes',
            new_name='current_votes',
        ),
    ]
