# Generated by Django 2.2.2 on 2019-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0012_auto_20191128_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_votes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
