# Generated by Django 2.2.2 on 2019-11-28 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0014_profile_last_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_vote',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
