# Generated by Django 2.2.2 on 2020-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0015_auto_20191128_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='backdrop_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
