# Generated by Django 2.2.2 on 2020-01-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0016_film_backdrop_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='backdrop_path',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster_path',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
