# Generated by Django 2.2.2 on 2020-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0019_film_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
