# Generated by Django 2.2.2 on 2020-01-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0020_film_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_id',
        ),
    ]
