# Generated by Django 2.2.2 on 2020-01-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0021_remove_film_film_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
    ]
