# Generated by Django 2.2.2 on 2020-02-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0023_film_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='in_current_vote',
        ),
    ]
