# Generated by Django 2.2.2 on 2020-02-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0024_remove_film_in_current_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='vote_count',
        ),
        migrations.AlterField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(default=1, null=True, unique=True),
        ),
    ]
