# Generated by Django 2.2.2 on 2020-02-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0025_auto_20200210_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.TextField(default='', null=True),
        ),
    ]
