# Generated by Django 2.2.2 on 2020-02-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0026_film_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genres',
            new_name='_genres',
        ),
    ]
