# Generated by Django 2.2.2 on 2020-03-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0028_filmconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmconfig',
            name='logo',
            field=models.ImageField(default='static/images/logo.png', upload_to='logo/'),
        ),
    ]
