# Generated by Django 2.2.2 on 2020-03-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0029_filmconfig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmconfig',
            name='logo_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='filmconfig',
            name='logo',
            field=models.ImageField(default='logo/default.png', upload_to='logo/'),
        ),
    ]
