# Generated by Django 3.0.6 on 2020-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0030_auto_20200310_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdb_id',
            field=models.TextField(default='', null=True),
        ),
    ]
