# Generated by Django 3.0.6 on 2020-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0031_film_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='imdb_id',
        ),
        migrations.AddField(
            model_name='film',
            name='score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=3, null=True),
        ),
    ]
