# Generated by Django 3.0.6 on 2020-06-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0032_auto_20200612_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmconfig',
            name='stylesheet',
            field=models.FileField(default='config/stylesheet.css', upload_to='config/'),
        ),
        migrations.AlterField(
            model_name='filmconfig',
            name='logo',
            field=models.ImageField(default='logo/default.png', upload_to='config/'),
        ),
    ]
