# Generated by Django 3.2 on 2021-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_management', '0033_auto_20200616_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmconfig',
            name='odd_weeks',
            field=models.BooleanField(default=False),
        ),
    ]
